# Create Services
services:
  ax25:
    image: ax25
    container_name: ax25
    hostname: ax25
    network_mode: host # to get ax ports working
    volumes:
      - conf:/etc/ax25
      - varl:/var/lib/ax25
      - varf:/var/ax25
      - opt:/opt
      - openvpn:/etc/openvpn
      - /lib/modules:/lib/modules
    environment:
      - TZ=Europe/Amsterdam
    privileged: true    # needed for ax25 to start properly
    # this can be removed if your not on hamnet / openvpn or chenge it (see crontab)
    healthcheck:
      test: "curl -f http://db0res.ampr.org"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

volumes:
  conf:
  opt:
  openvpn:
  varl:
  varf:
