# Create Services
services:
  ax25:
    image: ax25
    container_name: ax25
    hostname: ax25
    network_mode: host # to get ax ports working
    volumes:
      - conf:/etc/ax25
      - varl:/var/lib/ax25
      - varf:/var/ax25
      - opt:/opt
      - openvpn:/etc/openvpn
      - /lib/modules:/lib/modules
    privileged: true    # needed for ax25 to start properly

volumes:
  conf:
  opt:
  openvpn:
  varl:
  varf:
